[tox]
# ISSUE 012: Тестируем только py312, так как это единственная доступная версия
envlist = py312
toxworkdir = {env:TOX_WORK_DIR:.tox}

[testenv]
deps =
  -e .[dev]
setenv = HOME = {envtmpdir}
commands =
  pytest -v -m "not requires_tui and not requires_chrome and not requires_network"

[testenv:tui]
deps =
  -e .[dev,tui]
commands =
  pytest -v -m "requires_tui"

# ISSUE 019: Добавлен тестовый env для pylint
[testenv:lint]
deps =
  pylint>=3.0
  -e .
commands =
  pylint parser_2gis
