[tox]
envlist = flake8, mypy, py310, py311, py312
toxworkdir = {env:TOX_WORK_DIR:.tox}

[testenv]
deps =
  -e .[dev]
setenv = HOME = {envtmpdir}
commands =
  pytest -v -m "not requires_tui and not requires_chrome and not requires_network"

[testenv:flake8]
deps =
  flake8>=6.0
commands =
  flake8 parser_2gis

[testenv:mypy]
deps =
  mypy>=1.5.0
  types-requests>=2.31.0

commands =
  mypy {posargs}

[testenv:tui]
deps =
  -e .[dev,tui]
commands =
  pytest -v -m "requires_tui"
