[tox]
envlist = flake8, mypy, py310, py311, py312
toxworkdir = {env:TOX_WORK_DIR:.tox}

[testenv]
deps =
  -e .[dev]
setenv = HOME = {envtmpdir}
commands =
  pytest -v

[testenv:flake8]
deps =
  flake8>=6.0
commands =
  flake8 parser_2gis

[testenv:mypy]
deps =
  mypy>=1.5.0
  types-requests>=2.31.0

commands =
  mypy {posargs}
